//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.Web;
namespace ProductManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Products
    {
        public int ID { get; set; }

        
        [DisplayName("ProductName")]
        [Required]
        public string Name { get; set; }

       
        [DisplayName("Category")]
        [Required]
        public string Category { get; set; }

        
        [DisplayName("Price")]
        [Required]
        public decimal Price { get; set; }

        
        [DisplayName("Quantity")]
        [Required]
        public int Quantity { get; set; }

        
        [DisplayName("Description")]
        [Required]
        public string Description { get; set; }

        
        [DisplayName("ProductImage")]
        public string image_path { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
